<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!-- Windows 2004 -->
		<TargetFrameworks>net10.0-windows</TargetFrameworks>
		<IsPackable>false</IsPackable>
		<Platforms>x64</Platforms>
		<Configurations>Debug;Release;WinAzureTest;WinAzureRelease</Configurations>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
		<DebugType>embedded</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
		<DebugType>embedded</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>

	<!-- Azure pipelines debugging locally -->
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='WinAzureTest|x64'">
		<DebugType>embedded</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<DefineConstants>DEBUG;AZURE</DefineConstants>
	</PropertyGroup>

	<!-- Azure pipelines test run -->
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='WinAzureRelease|x64'">
		<DebugType>embedded</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<DefineConstants>AZURE</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.msbuild" Version="10.0.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
		<PackageReference Include="MSTest.TestAdapter" Version="4.3.2" />
		<PackageReference Include="MSTest.TestFramework" Version="4.3.2" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MassEffectModManagerCore\ME3TweaksModManager.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="7z64.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
