<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<!-- Windows 2004 -->
		<TargetFrameworks>net10.0-windows</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ValidateExecutableReferencesMatchSelfContained>false</ValidateExecutableReferencesMatchSelfContained>
		<Platforms>x64</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Pathoschild.FluentNexus" Version="1.0.5" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TestArchiveGenerator\TestArchiveGenerator.csproj" />
	</ItemGroup>

</Project>
