<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<!-- Windows 2004 -->
		<TargetFrameworks>net10.0-windows</TargetFrameworks>
		<PublishTrimmed>true</PublishTrimmed>
		    <PublishSingleFile>true</PublishSingleFile>
		    <PublishReadyToRun>true</PublishReadyToRun>
		    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<Platforms>x64</Platforms>
		<Version>1.0.1</Version>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\SevenZip\SevenZip.csproj" />
		<ProjectReference Include="..\MassEffectModManagerCore\ME3TweaksModManager.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="7z64.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
